artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shivammishra000/Data-sets/raw/refs/heads/main/samsum_data.zip
  loclal_data_file: artifacts/data_ingestion/samsum_data.zip
  unzip_dir: artifacts/data_ingestion